### ISSUE TITLE
The version name in elpa-macaulay2 is inconsistent with the version name used by setupEmacs()

### ISSUE THREAD

**Issue by Jazengm** [Macaulay2/M2-emacs#75]
I am trying to use emacs29 installed by snap, and the error message "cannot find M2.el" shows up. It turns out `.emacs-Macaulay2` tries to find `M2-init.el` under the directory `/usr/share/emacs/site-lisp/elpa-src/macaulay2-1.24.05`, but the actual directory is `/usr/share/emacs/site-lisp/elpa-src/macaulay2-1.24.5` (1.24.05 vs. 1.24.5). I suppose this directory was created when elpa-macaulay2 was automatically installed along with macaulay2, and at the same time this directory was added to the `load-path` of the emacs in the Ubuntu package (my WSL2 is using Ubuntu 22.04.3 LTS). This should explain why I can run M2 in Ubuntu's emacs but not in snap's emacs.

I think 1.24.05 is the correct one, since macaulay2.com is using it. Perhaps a simple update on elpa-macaulay2 can resolve this issue?

**Comment by mahrud** [comment]
Is `elpa-macaulay2` just the name of the Ubuntu package for the M2-mode? If so @d-torrance probably can help, otherwise I'm pretty sure M2-mode is not on ELPA.

**Comment by d-torrance** [comment]
Yes, `elpa-macaulay2` is just the name of the Debian/Ubuntu package.  It's a naming convention for Emacs packages in Debian and has nothing to do with whether something is actually on ELPA.

I'm aware of the version number issue -- `dh-elpa` (which handles the installation) does some sort of normalization of version numbers and strips the leading zero.  I haven't quite figured out how to stop this, but would like to figure it out at some point.  This won't be a problem for the November releases, but it will be the for May releases!

Thanks for pointing out the issue with the snap package!  I hadn't noticed it since I use the .deb package from the Ubuntu repos.  It's probably also a problem if someone were to install Emacs in some other manner, like compiling it from source. 

I'll play around with this some more.  If I can't figure out how to preserve the leading zero, then I can just have `setupEmacs` strip the leading zero, too.

**Comment by d-torrance** [comment]
Update: I don't think there's a way to keep `dh-elpa` from stripping the leading 0 -- it calls `(package-version-join (version-to-list "1.24.05"))` when determining the installation path.  I'll update the Ubuntu package in the PPA so that `setupEmacs()` uses the correct path.

**Comment by d-torrance** [comment]
@Jazengm -- I've updated the Macaulay2 package in the PPA so that `setupEmacs` should now correctly set the load path.
